swagger: "2.0"
info:
  version: "1.0.0"
  title: "Telegram Gateway API"
  description: "Gateway for receiving Telegram webhook updates and routing to internal services."
  contact:
    name: "NeuroMentor Team"
    email: "dev@neuroml.io"
host: localhost
x-go-package: github.com/telegram_gateway_service
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /webhook:
    post:
      summary: "Receive Telegram Update"
      description: "Handles incoming Telegram webhook updates."
      operationId: "handleTelegramWebhook"
      tags:
        - telegram
      parameters:
        - in: body
          name: update
          required: true
          schema:
            $ref: "#/definitions/TelegramUpdate"
      responses:
        200:
          description: "Successfully received"
        400:
          description: "Invalid input"
        500:
          description: "Internal error"

definitions:
  TelegramUser:
    type: object
    properties:
      id:
        type: integer
        format: int64
      is_bot:
        type: boolean
      first_name:
        type: string
      last_name:
        type: string
      username:
        type: string
      language_code:
        type: string

  TelegramChat:
    type: object
    properties:
      id:
        type: integer
        format: int64
      type:
        type: string
      title:
        type: string
      username:
        type: string
      first_name:
        type: string
      last_name:
        type: string

  TelegramMessage:
    type: object
    properties:
      message_id:
        type: integer
      from:
        $ref: "#/definitions/TelegramUser"
      chat:
        $ref: "#/definitions/TelegramChat"
      date:
        type: integer
        format: int64
      text:
        type: string

  TelegramCallbackQuery:
    type: object
    properties:
      id:
        type: string
      from:
        $ref: "#/definitions/TelegramUser"
      data:
        type: string
      message:
        $ref: "#/definitions/TelegramMessage"

  TelegramUpdate:
    type: object
    properties:
      update_id:
        type: integer
      message:
        $ref: "#/definitions/TelegramMessage"
      callback_query:
        $ref: "#/definitions/TelegramCallbackQuery"
